#-*- coding:utf-8 -*-
def foo():
    r=some_function();
    if r==(-1):
        return (-1)
    #do something
    return  r

def bar():
    r=foo()
    if r==(-1):
        print 'Error'
    else:
        pass

foo()
bar()
#不明白以上是为了干啥
#-*- coding:utf-8 -*-
try:
    print 'try..'
    r = 10/0
    print 'result:',r
except ZeroDivisionError,e:
    print 'except:',e
finally:
    print 'finally...'
print 'END'
#当我们认为某些代码可能会出错时，就可用try来运行这段代码，如果
#z执行出错，则后续代码不会继续执行，而是直接跳转至至错误处理代
# 码，即except语句块，执行完except后，如果有finally语句块，则
#执行finally语句块，至此，执行完毕。
